// src/pages/route-compare/index.tsx
import { useState, useEffect, useRef } from 'react'
import { View, Text, ScrollView, Map } from '@tarojs/components'
import Taro from '@tarojs/taro'
import RouteCard from '@/components/business/RouteCard'
import Icon from '@/components/base/Icon'
import { useRouteStore } from '@/stores/useRouteStore'
import { useSessionStore } from '@/stores/useSessionStore'
import { useUserStore } from '@/stores/useUserStore'  // getState() only
import { createInstantPlan, getTripRoutes, sortRoutesByPreference, getTripWaitingStatus, selectTripRoute } from '@/services/api'

import styles from './index.module.scss'

const STOP_COORDS: Record<string, { lat: number; lng: number }> = {
  's1': { lat: 31.2990, lng: 121.5120 },
  's2': { lat: 31.2978, lng: 121.5098 },
  's3': { lat: 31.2962, lng: 121.5085 },
  's4': { lat: 31.3025, lng: 121.5058 },
  's5': { lat: 31.2985, lng: 121.5025 },
  's6': { lat: 31.2998, lng: 121.5040 },
  's7': { lat: 31.3014, lng: 121.5145 },
  's8': { lat: 31.3005, lng: 121.5132 },
  's9': { lat: 31.2997, lng: 121.5118 },
}

const ROUTE_STOPS: Record<string, string[]> = {
  'route-1': ['s1', 's2', 's3'],
  'route-2': ['s4', 's5', 's6'],
  'route-3': ['s7', 's8', 's9'],
}

export default function RouteComparePage() {
  const selectedRouteId = useRouteStore(s => s.selectedRouteId)
  const selectRoute = useRouteStore(s => s.selectRoute)
  const setRoutes = useRouteStore(s => s.setRoutes)
  const storedRoutes = useRouteStore(s => s.routes)
  const { area, peopleCount, endTime, budgetPerPerson, sceneTags, categories, setSession, tripId } = useSessionStore.getState()

  const [routes, setLocalRoutes] = useState(storedRoutes)
  const [routesLoading, setRoutesLoading] = useState(storedRoutes.length === 0)
  const [expandedRouteId, setExpandedRouteId] = useState<string | null>(null)
  const [selecting, setSelecting] = useState(false)
  const [peerSelectedRouteId, setPeerSelectedRouteId] = useState<string | null>(null)
  const navigatingRef = useRef(false)

  useEffect(() => {
    // 直接从 store 读取 token，不依赖响应式订阅（避免 Taro 微信端 useEffect 依赖触发超时）
    const token = useUserStore.getState().token
    console.log('[route-compare] mount, token:', !!token, 'stored:', storedRoutes.length)
    if (storedRoutes.length > 0) {
      setLocalRoutes(sortRoutesByPreference(storedRoutes, { sceneTags, categories, budgetPerPerson }))
      setRoutesLoading(false)
      return
    }
    if (!token) {
      console.warn('[route-compare] no token on mount')
      setRoutesLoading(false)
      return
    }
    if (tripId) {
      // Multi-person flow: routes already generated by backend, just fetch them
      console.log('[route-compare] fetching pre-generated routes for trip:', tripId)
      getTripRoutes(tripId)
        .then((fetchedRoutes) => {
          console.log('[route-compare] routes received:', fetchedRoutes?.length, fetchedRoutes?.[0]?.name)
          const sorted = sortRoutesByPreference(fetchedRoutes, { sceneTags, categories, budgetPerPerson })
          setRoutes(sorted as any)
          setLocalRoutes(sorted as any)
        })
        .catch((e) => console.error('[route-compare] load routes error:', e))
        .finally(() => setRoutesLoading(false))
    } else {
      // Single-person flow: generate routes now
      console.log('[route-compare] calling createInstantPlan')
      createInstantPlan({ area, peopleCount, endTime, budgetPerPerson, sceneTags, categories })
        .then((res) => {
          console.log('[route-compare] routes received:', res.routes?.length, res.routes?.[0]?.name)
          setSession({ inviteCode: res.inviteCode })
          const sorted = sortRoutesByPreference(res.routes, { sceneTags, categories, budgetPerPerson })
          setRoutes(sorted as any)
          setLocalRoutes(sorted as any)
        })
        .catch((e) => console.error('[route-compare] load routes error:', e))
        .finally(() => setRoutesLoading(false))
    }
  }, [])  // eslint-disable-line react-hooks/exhaustive-deps

  // 多人模式：轮询 waiting-status，检测对方是否已选路线
  useEffect(() => {
    if (!tripId) return
    const poll = async () => {
      try {
        const status = await getTripWaitingStatus(tripId)
        if (status.selected_route_id && !navigatingRef.current) {
          setPeerSelectedRouteId(status.selected_route_id)
        }
      } catch (e) {
        // 轮询失败静默忽略
      }
    }
    poll()
    const timer = setInterval(poll, 5000)
    return () => clearInterval(timer)
  }, [tripId])  // eslint-disable-line react-hooks/exhaustive-deps

  const expandedRoute = expandedRouteId ? routes.find(r => r.id === expandedRouteId) : null

  const sheetMapData = expandedRoute ? (() => {
    const ids = ROUTE_STOPS[expandedRoute.id] ?? []
    const coords = ids.map(id => STOP_COORDS[id]).filter(Boolean)
    return {
      markers: coords.map((c, i) => ({ id: i, latitude: c.lat, longitude: c.lng, width: 24, height: 24 })),
      polyline: coords.length >= 2 ? [{
        points: coords.map(c => ({ latitude: c.lat, longitude: c.lng })),
        color: '#111111', width: 5, arrowLine: true,
      }] : [],
      centerLat: coords[0]?.lat ?? 31.2990,
      centerLng: coords[0]?.lng ?? 121.5120,
    }
  })() : null

  const handleExpand = (id: string) => {
    setExpandedRouteId(id)
  }

  const inviteCode = useSessionStore(s => s.inviteCode)

  const handleShare = () => {
    const code = inviteCode || '暂无邀请码'
    Taro.setClipboardData({
      data: `我在拼程规划了一条路线，邀请你一起来投票选路线！邀请码：${code}`,
      success: () => Taro.showToast({ title: '邀请信息已复制', icon: 'success', duration: 2000 }),
    })
  }

  const handleSelectAndEnter = async () => {
    if (!expandedRouteId || selecting || navigatingRef.current) return
    navigatingRef.current = true
    setSelecting(true)
    selectRoute(expandedRouteId)
    if (tripId) {
      try {
        await selectTripRoute(tripId, expandedRouteId)
      } catch (e) {
        console.error('[route-compare] selectTripRoute error:', e)
      }
    }
    setExpandedRouteId(null)
    Taro.navigateTo({ url: `/pages/route-detail/index?routeId=${expandedRouteId}&tripId=${tripId}` })
  }

  if (routesLoading) {
    return (
      <View className={styles.page}>
        <View className={styles.header}>
          <Text className={styles.titleSmall}>AI 正在生成路线...</Text>
        </View>
      </View>
    )
  }

  return (
    <View className={styles.page}>
      <View className={styles.header}>
        <Text className={styles.titleSmall}>{peopleCount === 1 ? '为你生成了' : '为你们生成了'}</Text>
        <Text className={styles.titleBig}>{routes.length} 条路线</Text>
        <Text className={styles.subtitle}>{`${area || '出发地'} · ${peopleCount}人成行 · ${endTime}前结束`}</Text>
      </View>

      {/* 同伴已选路线通知 banner */}
      {peerSelectedRouteId && !navigatingRef.current && (
        <View className={styles.peerBanner}>
          <View className={styles.peerBannerLeft}>
            <Text className={styles.peerBannerDot} />
            <View>
              <Text className={styles.peerBannerTitle}>同伴已选好路线</Text>
              <Text className={styles.peerBannerSub}>
                {routes.find(r => r.id === peerSelectedRouteId)?.name || '查看他们的选择'}
              </Text>
            </View>
          </View>
          <View className={styles.peerBannerBtn} onClick={() => {
            navigatingRef.current = true
            selectRoute(peerSelectedRouteId)
            Taro.navigateTo({ url: `/pages/route-detail/index?routeId=${peerSelectedRouteId}&tripId=${tripId}` })
          }}>
            <Text className={styles.peerBannerBtnText}>去看看</Text>
          </View>
        </View>
      )}

      {/* 邀请好友一起选（多人出行才显示） */}
      {peopleCount > 1 && !peerSelectedRouteId && (
        <View className={styles.inviteBanner}>
          <View className={styles.inviteBannerLeft}>
            <Text className={styles.inviteBannerTitle}>叫好友一起来选</Text>
            <Text className={styles.inviteBannerSub}>分享路线，大家投票决定去哪</Text>
          </View>
          <View className={styles.inviteBannerBtn} onClick={handleShare}>
            <Text className={styles.inviteBannerBtnText}>复制邀请</Text>
          </View>
        </View>
      )}

      <View className={styles.list}>
        {routes.map((route, i) => (
          <View
            key={route.id}
            className={styles.cardWrap}
            style={{ animationDelay: `${i * 100 + 60}ms` }}
          >
            <RouteCard
              route={route}
              isSelected={selectedRouteId === route.id}
              onExpand={handleExpand}
            />
          </View>
        ))}
      </View>

      {/* AI 改行程悬浮按钮 */}
      {!expandedRoute && (
        <View
          className={styles.aiFab}
          onClick={() => Taro.navigateTo({ url: '/pages/assistant/index' })}
        >
          <Text className={styles.aiFabIcon}>✦</Text>
          <Text className={styles.aiFabText}>AI 规划</Text>
        </View>
      )}

      {/* 详情半屏 Sheet */}
      {expandedRoute && (
        <View className={styles.sheetMask} onClick={() => setExpandedRouteId(null)}>
          <View className={styles.sheet} onClick={e => e.stopPropagation()}>
            <View className={styles.sheetHandle} />

            {/* 地图大图 — 真实 Map */}
            <View className={styles.sheetMap}>
              {sheetMapData && (
                <Map
                  className={styles.sheetMapEl}
                  latitude={sheetMapData.centerLat}
                  longitude={sheetMapData.centerLng}
                  scale={14}
                  markers={sheetMapData.markers as any}
                  polyline={sheetMapData.polyline as any}
                  enableZoom={false}
                  enableScroll={false}
                  enableRotate={false}
                  style={{ width: '100%', height: '100%', display: 'block' }}
                />
              )}
              <View className={styles.sheetMapOverlay} />
              {expandedRoute.isAiRecommended && (
                <View className={styles.sheetBadge}>AI推荐</View>
              )}
            </View>

            <ScrollView scrollY className={styles.sheetBody} style={{ height: '100%' }}>
              <View className={styles.sheetBodyInner}>
              {/* 路线名 + 数据 */}
              <Text className={styles.sheetName}>{expandedRoute.name}</Text>

              <View className={styles.sheetDataRow}>
                <View className={styles.sheetDataItem}>
                  <View className={styles.sheetDataValueRow}>
                    <Text className={styles.sheetDataValue}>{expandedRoute.budgetPerPerson}</Text>
                    <Text className={styles.sheetDataUnit}>¥</Text>
                  </View>
                  <Text className={styles.sheetDataLabel}>人均消费</Text>
                </View>
                <View className={styles.sheetDivider} />
                <View className={styles.sheetDataItem}>
                  <View className={styles.sheetDataValueRow}>
                    <Text className={styles.sheetDataValue}>{(expandedRoute.totalMinutes / 60).toFixed(1)}</Text>
                    <Text className={styles.sheetDataUnit}>h</Text>
                  </View>
                  <Text className={styles.sheetDataLabel}>总时长</Text>
                </View>
                <View className={styles.sheetDivider} />
                <View className={styles.sheetDataItem}>
                  <View className={styles.sheetDataValueRow}>
                    <Text className={styles.sheetDataValue}>{expandedRoute.walkDistanceM}</Text>
                    <Text className={styles.sheetDataUnit}>m</Text>
                  </View>
                  <Text className={styles.sheetDataLabel}>步行距离</Text>
                </View>
              </View>

              {/* 站点时间轴 */}
              <Text className={styles.sheetSectionTitle}>行程安排</Text>
              <View className={styles.timeline}>
                {expandedRoute.stops.map((stop, i) => (
                  <View key={stop.id} className={styles.timelineItem}>
                    <View className={styles.timelineDot} />
                    {i < expandedRoute.stops.length - 1 && (
                      <View className={styles.timelineLine} />
                    )}
                    <View className={styles.timelineContent}>
                      <Text className={styles.timelineName}>{stop.name}</Text>
                      <Text className={styles.timelineDuration}>约 {stop.stayMinutes} 分钟</Text>
                      <View className={styles.timelineTags}>
                        {stop.tags.map(t => (
                          <Text key={t} className={styles.timelineTag}>{t}</Text>
                        ))}
                      </View>
                    </View>
                  </View>
                ))}
              </View>

              {/* 选择按钮 — ScrollView 末尾，始终可触达 */}
              <View className={styles.inlineSelectBtn} onClick={handleSelectAndEnter}>
                <Text className={styles.inlineSelectBtnText}>
                  {selecting ? '确认中...' : selectedRouteId === expandedRouteId ? '✓ 已选择，进入行程' : '选择这条路线，通知大家'}
                </Text>
              </View>
              </View>{/* sheetBodyInner end */}
            </ScrollView>
          </View>
        </View>
      )}
    </View>
  )
}
